name: opengatellm-ci

services:
  api:
    build:
      context: ..
      dockerfile: app/Dockerfile
    restart: always
    env_file: "${APP_ENV_FILE:-.env.ci}"
    volumes:
      - ../scripts/generate_configuration_documentation.py:/scripts/generate_configuration_documentation.py:ro
    ports:
      - 8080:8000
    environment:
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - ALBERT_API_KEY=${ALBERT_API_KEY}
      - COVERAGE_RCFILE=./app/.coveragerc
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  postgres:
    extends:
      file: ../compose.yml
      service: postgres

  redis:
    extends:
      file: ../compose.yml
      service: redis

  secretiveshell:
    extends:
      file: ../compose.yml
      service: secretiveshell

  elasticsearch:
    extends:
      file: ../compose.yml
      service: elasticsearch
      
volumes:
  postgres:
  redis:
  elasticsearch:
