# ----------------------------------- models ------------------------------------
models:
  - name: albert-testbed
    type: text-generation
    providers:
      - type: vllm
        url: http://albert-testbed.etalab.gouv.fr:8000
        model_name: "gemma3:1b"
      
  # - name: # required - example: my-llm
  #   type: # required - values: text-image-to-text, text-generation, text-embeddings-inference
  #   aliases: # optional - example: ["model-alias"]
  #   owned_by: # optional - example: "Me"
  #   routing_strategy: # optional - default: shuffle - values: shuffle, round_robin
  #   providers:
  #     - type: # required - example: "openai" - values: vllm, tei, openai, albert
  #       url: # required - example: "https://api.openai.com" (without /v1 suffix)
  #       key: # required - example: "sk-1234567890"
  #       timeout: # optional - default: 10
  #       model_name: # required - example: "gpt-4o"
  #       model_cost_prompt_tokens: # optional - default: None - example: 0.10
  #       model_cost_completion_tokens: # optional - default: None - example: 0.10
  #       model_carbon_footprint_zone: # optional - default: "WOR" - values: country codes (ISO 3166-1 alpha-3 format)
  #       model_carbon_footprint_total_params: # optional - default: None - example: 8
  #       model_carbon_footprint_active_params: # optional - default: None - example: 8

# -------------------------------- dependencies ---------------------------------
dependencies:
  postgres: # required
    url: postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeme}@${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5432}/api
    echo: False
    pool_size: 5
    connect_args:
      server_settings:
        statement_timeout: "120s"
      command_timeout: 60

  redis: # required
      host: ${REDIS_HOST:-localhost}
      port: ${REDIS_PORT:-6379}
playground:
  api_url: http://${API_HOST}:8000

auth:
  master_username: master
  master_key: changeme

oauth2:
  client_id: ${PROCONNECT_CLIENT_ID}
  client_secret: ${PROCONNECT_CLIENT_SECRET}
  server_metadata_url: https://identite-sandbox.proconnect.gouv.fr/.well-known/openid-configuration
  redirect_uri: ${OAUTH2_REDIRECT_URI}
  scope: "openid profile email"
  allowed_domains:
    - localhost
    - gouv.fr
  default_role: Freemium
  encryption_key: ${OAUTH2_ENCRYPTION_KEY}  # Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"

session_secret_key: ${SESSION_SECRET_KEY}

monitoring:
  postgres:
    enabled: true

mcp:
  mcp_bridge_url: http://${MCP_BRIDGE_HOST}:${MCP_BRIDGE_PORT}

databases:
  - type: elasticsearch
    context: api
    model: my-embeddings-model
    args:
      hosts: http://${ELASTICSEARCH_HOST}:9200
      basic_auth:
        - "elastic"
        - "changeme"

  - type: redis
    context: api
    args:
      host: ${REDIS_HOST}
      password: changeme

  # qdrant: # optional
  # elastic: # optional
  # marker: # optional
  # albert: # optional
  # brave: # optional
  # duckduckgo: # optional
  # secretiveshell: # optional
  # sentry: # optional

# ---------------------------------- settings -----------------------------------
# settings:

  # disabled_routers: # optional - default: [] - values: ["agents", "audio", "chat", "chunks", "collections", "completions", "documents", "embeddings", "files", "models", "ocr", "parse", "rerank", "roles", "search", "tokens", "users", "usage"]

  # usage_tokenizer: # optional - default: tiktoken_gpt2 - values: tiktoken_gpt2, tiktoken_r50k_base, tiktoken_p50k_base, tiktoken_p50k_edit, tiktoken_cl100k_base, tiktoken_o200k_base

  # log_level: # optional - default: INFO - values: DEBUG, INFO, WARNING, ERROR, CRITICAL
  # log_format: # optional - default: "[%(asctime)s][%(process)d:%(name)s][%(levelname)s] %(client_ip)s - %(message)s"

  # swagger_title: # optional - default: OpenGateLLM
  # swagger_version: # optional - default: 1.0.0
  # swagger_contact_url: # optional - default: https://github.com/etalab-ia/OpenGateLLM
  # swagger_contact_email: # optional - default: None - example: john.doe@example.com
  # swagger_docs_url: # optional - default: /docs
  # swagger_redoc_url: # optional - default: /redoc

  # mcp_max_iterations: # optional - default: 2

  # auth_master_username: # optional - default: master
  # auth_master_key: # optional - default: changeme
  # auth_max_token_expiration_days: # optional - default: None, ex: 365

  # rate_limiting_strategy: # optional - default: fixed_window - values: fixed_window, sliding_window

  # monitoring_sentry_enabled: # optional - default: False
  # monitoring_postgres_enabled: # optional - default: False
  # monitoring_prometheus_enabled: # optional - default: False

  # vector_store_model: # optional - default: None - required if elasticsearch or qdrant in dependencies - example: "my-model"

  # search_web_query_model: # optional - default: None - required if brave or duckduckgo in dependencies
  # search_web_limited_domains: # optional - default: None - example: ["google.com", "wikipedia.org"]
  # search_web_user_agent: # optional - default: None

  # search_multi_agents_synthesis_model: # optional - default: None - example: "my-model"
  # search_multi_agents_reranker_model: # optional - default: None - example: "my-model"


  # playground ---------------------------------------------------------------------------------------------------------------------------------------
playground:
  api_url: http://${API_HOST:-localhost}:8080
  postgres:
    url: postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeme}@${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5432}/playground
  # auth_master_username: master # optional - default: master
  # auth_master_key: changeme # optional - default: changeme