"""Init database

Revision ID: 6089e7caef71
Revises:
Create Date: 2025-03-07 08:43:18.613794

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6089e7caef71"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_id", sa.String(), nullable=True),
        sa.Column("default", sa.Boolean(), nullable=True),
        sa.Column("admin", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_display_id"), "role", ["display_id"], unique=True)
    op.create_index(op.f("ix_role_id"), "role", ["id"], unique=False)
    op.create_index("only_one_default_role", "role", ["default"], unique=True, postgresql_where=sa.text('"default"'))
    op.create_table(
        "rate_limit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.String(), nullable=False),
        sa.Column("type", sa.Enum("RPD", "RPM", "TPM", name="ratelimittype"), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rate_limit_id"), "rate_limit", ["id"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_id", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("budget_allocation", sa.Float(), nullable=True),
        sa.Column("budget_reset", sa.Enum("HOUR", "DAY", "MONTH", "YEAR", name="budgetreset"), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_display_id"), "user", ["display_id"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("display_id", sa.String(), nullable=True),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "display_id", name="unique_token_display_id_per_user"),
    )
    op.create_index(op.f("ix_token_id"), "token", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_id"), table_name="token")
    op.drop_table("token")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_display_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_rate_limit_id"), table_name="rate_limit")
    op.drop_table("rate_limit")
    op.drop_index("only_one_default_role", table_name="role", postgresql_where=sa.text('"default"'))
    op.drop_index(op.f("ix_role_id"), table_name="role")
    op.drop_index(op.f("ix_role_display_id"), table_name="role")
    op.drop_table("role")
    # ### end Alembic commands ###
