"""remove default role attribut

Revision ID: 5553fa60acfa
Revises: 896cbf4c2cbb
Create Date: 2025-05-12 16:13:49.420409

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5553fa60acfa"
down_revision: Union[str, None] = "896cbf4c2cbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("only_one_default_role", table_name="role", postgresql_where='"default"')
    op.drop_column("role", "default")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("role", sa.Column("default", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index("only_one_default_role", "role", ["default"], unique=True, postgresql_where='"default"')
    # ### end Alembic commands ###
