"""Add new columns to usages table

Revision ID: 896cbf4c2cbb
Revises: 8c5ae2a3d4d0
Create Date: 2025-04-17 12:01:15.970424

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "896cbf4c2cbb"
down_revision: Union[str, None] = "a4ac45e7c990"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usage", sa.Column("time_to_first_token", sa.Integer(), nullable=True))
    op.add_column("usage", sa.Column("request_model", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage", "request_model")
    op.drop_column("usage", "time_to_first_token")
    # ### end Alembic commands ###
