"""add environnement impact in db

Revision ID: 37d92be0a44c
Revises: 752279f74929
Create Date: 2025-06-16 10:29:35.219844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37d92be0a44c'
down_revision: Union[str, None] = '752279f74929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage', sa.Column('kwh_min', sa.Float(), nullable=True))
    op.add_column('usage', sa.Column('kwh_max', sa.Float(), nullable=True))
    op.add_column('usage', sa.Column('kgco2eq_min', sa.Float(), nullable=True))
    op.add_column('usage', sa.Column('kgco2eq_max', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage', 'kgco2eq_max')
    op.drop_column('usage', 'kgco2eq_min')
    op.drop_column('usage', 'kwh_max')
    op.drop_column('usage', 'kwh_min')
    # ### end Alembic commands ###
