"""db schema for model router, client and routeralias

Revision ID: 6a6e053368f8
Revises: 37d92be0a44c
Create Date: 2025-07-16 22:39:46.979230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6e053368f8'
down_revision: Union[str, None] = '37d92be0a44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelrouter',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('routing_strategy', sa.String(), nullable=False),
    sa.Column('from_config', sa.Boolean(), nullable=False),
    sa.Column('owned_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_modelrouter_name'), 'modelrouter', ['name'], unique=False)
    op.create_table('modelclient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_carbon_footprint_zone', sa.String(), nullable=False),
    sa.Column('model_carbon_footprint_total_params', sa.Integer(), nullable=True),
    sa.Column('model_carbon_footprint_active_params', sa.Integer(), nullable=True),
    sa.Column('model_cost_prompt_tokens', sa.Float(), nullable=False),
    sa.Column('model_cost_completion_tokens', sa.Float(), nullable=False),
    sa.Column('metrics_retention_ms', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('model_router_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['model_router_name'], ['modelrouter.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelclient_id'), 'modelclient', ['id'], unique=False)
    op.create_table('modelrouteralias',
    sa.Column('name', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('model_router_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['model_router_name'], ['modelrouter.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_modelrouteralias_name'), 'modelrouteralias', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modelrouteralias_name'), table_name='modelrouteralias')
    op.drop_table('modelrouteralias')
    op.drop_index(op.f('ix_modelclient_id'), table_name='modelclient')
    op.drop_table('modelclient')
    op.drop_index(op.f('ix_modelrouter_name'), table_name='modelrouter')
    op.drop_table('modelrouter')
    # ### end Alembic commands ###
