"""remove delete cascade usage token id

Revision ID: 8c5ae2a3d4d0
Revises: e78eaed1bcb2
Create Date: 2025-04-04 16:41:52.058857

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8c5ae2a3d4d0"
down_revision: Union[str, None] = "e78eaed1bcb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("usage_token_id_fkey", "usage", type_="foreignkey")
    op.create_foreign_key(None, "usage", "token", ["token_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "usage", type_="foreignkey")
    op.create_foreign_key("usage_token_id_fkey", "usage", "token", ["token_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###
