"""remove unique name on token and collection

Revision ID: a4ac45e7c990
Revises: 8c5ae2a3d4d0
Create Date: 2025-04-15 15:13:33.886841

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a4ac45e7c990"
down_revision: Union[str, None] = "8c5ae2a3d4d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_collection_name_per_user", "collection", type_="unique")
    op.drop_constraint("unique_token_name_per_user", "token", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_token_name_per_user", "token", ["user_id", "name"])
    op.create_unique_constraint("unique_collection_name_per_user", "collection", ["user_id", "name"])
    # ### end Alembic commands ###
