"""add cost and budget colonne

Revision ID: 752279f74929
Revises: 5553fa60acfa
Create Date: 2025-05-28 15:41:27.302543

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "752279f74929"
down_revision: Union[str, None] = "5553fa60acfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usage", sa.Column("cost", sa.Float(), nullable=True))
    op.add_column("user", sa.Column("budget", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "budget")
    op.drop_column("usage", "cost")
    # ### end Alembic commands ###
