"""add auth

Revision ID: e78eaed1bcb2
Revises: 9a9c82ec2470
Create Date: 2025-04-02 16:03:52.675412

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e78eaed1bcb2"
down_revision: Union[str, None] = "9a9c82ec2470"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_id"), "role", ["id"], unique=False)
    op.create_index(op.f("ix_role_name"), "role", ["name"], unique=True)
    op.create_index("only_one_default_role", "role", ["default"], unique=True, postgresql_where=sa.text('"default"'))
    op.create_table(
        "limit",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("type", sa.Enum("TPM", "TPD", "RPM", "RPD", name="limittype"), nullable=False),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "model", "type", name="unique_rate_limit_per_role"),
    )
    op.create_index(op.f("ix_limit_id"), "limit", ["id"], unique=False)
    op.create_table(
        "permission",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column(
            "permission",
            sa.Enum(
                "CREATE_ROLE",
                "READ_ROLE",
                "UPDATE_ROLE",
                "DELETE_ROLE",
                "CREATE_USER",
                "READ_USER",
                "UPDATE_USER",
                "DELETE_USER",
                "CREATE_PUBLIC_COLLECTION",
                "READ_METRIC",
                name="permissiontype",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "permission", name="unique_permission_per_role"),
    )
    op.create_index(op.f("ix_permission_id"), "permission", ["id"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_name"), "user", ["name"], unique=True)
    op.create_table(
        "collection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("visibility", sa.Enum("PRIVATE", "PUBLIC", name="collectionvisibility"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="unique_collection_name_per_user"),
    )
    op.create_index(op.f("ix_collection_id"), "collection", ["id"], unique=False)
    op.create_table(
        "token",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="unique_token_name_per_user"),
    )
    op.create_index(op.f("ix_token_id"), "token", ["id"], unique=False)
    op.create_table(
        "document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["collection_id"], ["collection.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_document_id"), "document", ["id"], unique=False)
    op.add_column("usage", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column("usage", sa.Column("token_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "usage", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "usage", "token", ["token_id"], ["id"], ondelete="CASCADE")
    op.drop_column("usage", "user")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usage", sa.Column("user", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, "usage", type_="foreignkey")
    op.drop_constraint(None, "usage", type_="foreignkey")
    op.drop_column("usage", "token_id")
    op.drop_column("usage", "user_id")
    op.drop_index(op.f("ix_document_id"), table_name="document")
    op.drop_table("document")
    op.drop_index(op.f("ix_token_id"), table_name="token")
    op.drop_table("token")
    op.drop_index(op.f("ix_collection_id"), table_name="collection")
    op.drop_table("collection")
    op.drop_index(op.f("ix_user_name"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_permission_id"), table_name="permission")
    op.drop_table("permission")
    op.drop_index(op.f("ix_limit_id"), table_name="limit")
    op.drop_table("limit")
    op.drop_index("only_one_default_role", table_name="role", postgresql_where=sa.text('"default"'))
    op.drop_index(op.f("ix_role_name"), table_name="role")
    op.drop_index(op.f("ix_role_id"), table_name="role")
    op.drop_table("role")
    # ### end Alembic commands ###
