"""Add cumulative_calls column to usage table

Revision ID: 13ae3a13d5bc
Revises: 5553fa60acfa
Create Date: 2025-05-23 13:51:53.089811

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13ae3a13d5bc"
down_revision: Union[str, None] = "5553fa60acfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usage", sa.Column("cumulative_calls", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage", "cumulative_calls")
    # ### end Alembic commands ###
