"""db schema for model router, client and routeralias

Revision ID: 7a0cb766ba1e
Revises: 37d92be0a44c
Create Date: 2025-07-21 14:04:32.227699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0cb766ba1e'
down_revision: Union[str, None] = '37d92be0a44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('routing_strategy', sa.String(), nullable=False),
    sa.Column('owned_by', sa.String(), nullable=False),
    sa.Column('vector_size', sa.Integer(), nullable=True),
    sa.Column('max_context_length', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('from_config', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_model_name'), 'model', ['name'], unique=False)
    op.create_table('model_alias',
    sa.Column('name', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('model_router_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['model_router_name'], ['model.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_model_alias_name'), 'model_alias', ['name'], unique=False)
    op.create_table('model_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_cost_prompt_tokens', sa.Float(), nullable=True),
    sa.Column('model_cost_completion_tokens', sa.Float(), nullable=True),
    sa.Column('model_carbon_footprint_zone', sa.String(), nullable=True),
    sa.Column('model_carbon_footprint_total_params', sa.Integer(), nullable=True),
    sa.Column('model_carbon_footprint_active_params', sa.Integer(), nullable=True),
    sa.Column('model_router_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['model_router_name'], ['model.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_client_id'), 'model_client', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_client_id'), table_name='model_client')
    op.drop_table('model_client')
    op.drop_index(op.f('ix_model_alias_name'), table_name='model_alias')
    op.drop_table('model_alias')
    op.drop_index(op.f('ix_model_name'), table_name='model')
    op.drop_table('model')
    # ### end Alembic commands ###
