"""add budget colonne

Revision ID: 42db359bfa8a
Revises: 5553fa60acfa
Create Date: 2025-05-26 18:47:28.769343

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42db359bfa8a"
down_revision: Union[str, None] = "5553fa60acfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usage", sa.Column("budget", sa.Float(), nullable=True))
    op.add_column("user", sa.Column("budget", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "budget")
    op.drop_column("usage", "budget")
    # ### end Alembic commands ###
