"""Remove API key column

Revision ID: 28d8232bee22
Revises: c0bfeeca22a9
Create Date: 2025-07-29 10:40:18.103365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28d8232bee22"
down_revision: Union[str, None] = "c0bfeeca22a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "api_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("api_key", sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
