"""remove expires at column

Revision ID: 3ad8934ab327
Revises: 647433280fa7
Create Date: 2025-04-07 14:10:00.281290

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3ad8934ab327"
down_revision: Union[str, None] = "647433280fa7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "expires_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
