import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/quickstart',
        'getting-started/CONTRIBUTING',
        'getting-started/config',
        'getting-started/configuration',
      ],
    },
    {
      type: 'category',
      label: 'Functionalities',
      items: [
        'functionalities/budget',
        'functionalities/environmental_footprint',
        'functionalities/iam',
        'functionalities/search',
      ],
    },
    {
      type: 'category',
      label: 'Models',
      items: ['models/models', 'models/routing'],
    },
    {
      type: 'doc',
      id: 'architecture',
    },
    {
      type: 'doc',
      id: 'deployment',
    },
  ],
};

export default sidebars;
