import os

BASE_URL = os.getenv("BASE_URL", "http://localhost:8080/v1")
MODEL_TYPE__EMBEDDINGS = "text-embeddings-inference"
MODEL_TYPE__LANGUAGE = "text-generation"
MODEL_TYPE__AUDIO = "automatic-speech-recognition"
MODEL_TYPE__RERANK = "text-classification"
COLLECTION_DISPLAY_ID__INTERNET = "internet"
COLLECTION_TYPE__PRIVATE = "private"
CACHE_TTL = 1800  # 30 minutes
SUPPORTED_LANGUAGES = [
    "afrikaans",
    "albanian",
    "amharic",
    "arabic",
    "armenian",
    "assamese",
    "azerbaijani",
    "bashkir",
    "basque",
    "belarusian",
    "bengali",
    "bosnian",
    "breton",
    "bulgarian",
    "burmese",
    "cantonese",
    "castilian",
    "catalan",
    "chinese",
    "croatian",
    "czech",
    "danish",
    "dutch",
    "english",
    "estonian",
    "faroese",
    "finnish",
    "flemish",
    "french",
    "galician",
    "georgian",
    "german",
    "greek",
    "gujarati",
    "haitian",
    "haitian creole",
    "hausa",
    "hawaiian",
    "hebrew",
    "hindi",
    "hungarian",
    "icelandic",
    "indonesian",
    "italian",
    "japanese",
    "javanese",
    "kannada",
    "kazakh",
    "khmer",
    "korean",
    "lao",
    "latin",
    "latvian",
    "letzeburgesch",
    "lingala",
    "lithuanian",
    "luxembourgish",
    "macedonian",
    "malagasy",
    "malay",
    "malayalam",
    "maltese",
    "mandarin",
    "maori",
    "marathi",
    "moldavian",
    "moldovan",
    "mongolian",
    "myanmar",
    "nepali",
    "norwegian",
    "nynorsk",
    "occitan",
    "panjabi",
    "pashto",
    "persian",
    "polish",
    "portuguese",
    "punjabi",
    "pushto",
    "romanian",
    "russian",
    "sanskrit",
    "serbian",
    "shona",
    "sindhi",
    "sinhala",
    "sinhalese",
    "slovak",
    "slovenian",
    "somali",
    "spanish",
    "sundanese",
    "swahili",
    "swedish",
    "tagalog",
    "tajik",
    "tamil",
    "tatar",
    "telugu",
    "thai",
    "tibetan",
    "turkish",
    "turkmen",
    "ukrainian",
    "urdu",
    "uzbek",
    "valencian",
    "vietnamese",
    "welsh",
    "yiddish",
    "yoruba",
]
