name: Generate documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call: # Add this to make the workflow reusable
  workflow_dispatch: # Add this to allow manual triggering

jobs:
  generate_documentation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: |
        cp .github/.env.ci.example .github/.env.ci
        make test-integ action=up execute=docker
      env:
        BRAVE_API_KEY: ${{ secrets.BRAVE_API_KEY }}
        ALBERT_API_KEY: ${{ secrets.ALBERT_API_KEY }}

    - name: Generate configuration documentation
      run: |
        docker compose -f .github/compose.ci.yml --env-file .github/.env.ci exec -T api \
          python /scripts/generate_configuration_documentation.py --output /app/configuration.md
        
        docker compose -f .github/compose.ci.yml --env-file .github/.env.ci exec -T api \
          cat /app/configuration.md > ./docs/configuration.md

    - name: Commit configuration documentation
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update configuration documentation
        file_pattern: ./docs/configuration.md